# Generated by Django 3.2.8 on 2021-10-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_name', models.CharField(max_length=200)),
                ('bar_rating', models.FloatField(default=0.0)),
                ('bar_occupancy', models.IntegerField(default=0)),
                ('bar_capacity', models.IntegerField(default=0)),
            ],
        ),
    ]
