# Generated by Django 3.1.2 on 2021-10-27 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_name', models.CharField(max_length=200)),
                ('bar_rating', models.FloatField(default=0.0)),
                ('bar_capacity', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)])),
                ('bar_occupancy', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)])), django.core.validators.MinValueValidator(0)])),
                ('bar_url', models.CharField(max_length=300)),
            ],
        ),
    ]
